// Generated by https://quicktype.io

import Grid from "@mui/material/Unstable_Grid2/Grid2";
import Typography from "@mui/material/Typography";
import Link from "@mui/material/Link";
import type { Track, Artist } from "@/types/SpotifyAPI";
// import Link from "next/link";

export default function TopTracks({ songs }: { songs: Track[] }) {
  const artistsObj = (artists: Artist[]) => {
    return artists.map((artists, j) => {
      const artist = artists.name;
      const artistPopularity = artists.popularity;
      return (
        <Grid container xs={12} key={"artist-" + artist}>
          <Grid xs={artistPopularity ? 10 : 12}>
            <Typography key={"artist-name" + artist}>{artist}</Typography>
          </Grid>
          {artistPopularity && (
            <Grid xs={2}>
              <Typography key={"artist-popularity-" + artist}>
                {artistPopularity}
              </Typography>
            </Grid>
          )}
        </Grid>
      );
    });
  };
  const tracks = songs.map((song: Track, i: number) => {
    const { name, preview_url, external_urls, duration_ms, artists } = song;
    return (
      <Grid container xs={12} key={name + "_" + i + "-grid-container"}>
        <Grid xs={10}>
          <Typography key={"song-" + name}>{name}</Typography>;
        </Grid>
        <Grid xs={2}>
          <Typography key={"duration_ms-" + name}>{duration_ms}ms</Typography>
        </Grid>
        <Grid xs={12}>
          <Typography key={"spotify-url-" + name}>
            <Link href={external_urls.spotify}>external_urls.spotify</Link>
          </Typography>
        </Grid>
        <Grid container xs={12} key={"artists-" + name}>
          {artistsObj(artists)}
        </Grid>
        {preview_url && (
          <Grid xs={12}>
            <Link href={preview_url}>Preview</Link>
          </Grid>
        )}
      </Grid>
    );
  });

  return <Grid container>{tracks}</Grid>;
}
